// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=../../internal/mocks/mock_event_adapter.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	event "github.com/byron1st/integridb/pkg/event"
	gomock "go.uber.org/mock/gomock"
)

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
	isgomock struct{}
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter {
	mock := &MockAdapter{ctrl: ctrl}
	mock.recorder = &MockAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	return m.recorder
}

// GetEventByID mocks base method.
func (m *MockAdapter) GetEventByID(ctx context.Context, eventID string) (*event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventByID", ctx, eventID)
	ret0, _ := ret[0].(*event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventByID indicates an expected call of GetEventByID.
func (mr *MockAdapterMockRecorder) GetEventByID(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventByID", reflect.TypeOf((*MockAdapter)(nil).GetEventByID), ctx, eventID)
}

// GetEvents mocks base method.
func (m *MockAdapter) GetEvents(ctx context.Context, tableName, rowID string) ([]*event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvents", ctx, tableName, rowID)
	ret0, _ := ret[0].([]*event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvents indicates an expected call of GetEvents.
func (mr *MockAdapterMockRecorder) GetEvents(ctx, tableName, rowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvents", reflect.TypeOf((*MockAdapter)(nil).GetEvents), ctx, tableName, rowID)
}

// GetEventsByTable mocks base method.
func (m *MockAdapter) GetEventsByTable(ctx context.Context, tableName string) ([]*event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByTable", ctx, tableName)
	ret0, _ := ret[0].([]*event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByTable indicates an expected call of GetEventsByTable.
func (mr *MockAdapterMockRecorder) GetEventsByTable(ctx, tableName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByTable", reflect.TypeOf((*MockAdapter)(nil).GetEventsByTable), ctx, tableName)
}

// GetLastEvent mocks base method.
func (m *MockAdapter) GetLastEvent(ctx context.Context, tableName, rowID string) (*event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastEvent", ctx, tableName, rowID)
	ret0, _ := ret[0].(*event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastEvent indicates an expected call of GetLastEvent.
func (mr *MockAdapterMockRecorder) GetLastEvent(ctx, tableName, rowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastEvent", reflect.TypeOf((*MockAdapter)(nil).GetLastEvent), ctx, tableName, rowID)
}

// InsertEvent mocks base method.
func (m *MockAdapter) InsertEvent(ctx context.Context, arg1 *event.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEvent", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEvent indicates an expected call of InsertEvent.
func (mr *MockAdapterMockRecorder) InsertEvent(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEvent", reflect.TypeOf((*MockAdapter)(nil).InsertEvent), ctx, arg1)
}
